
DROP TABLE Itens_Chamado CASCADE CONSTRAINTS;
DROP TABLE Funcionario_Chamado CASCADE CONSTRAINTS;
DROP TABLE Chamado CASCADE CONSTRAINTS;
DROP TABLE Dispositivo CASCADE CONSTRAINTS;
DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Funcionario CASCADE CONSTRAINTS;
DROP TABLE Produto CASCADE CONSTRAINTS;
DROP TABLE Log_Auditoria CASCADE CONSTRAINTS;


CREATE TABLE Cliente (
    Id_Cliente NUMBER PRIMARY KEY,
    Nome VARCHAR2(50) NOT NULL,
    Sobrenome VARCHAR2(50),
    Data_Nasc DATE,
    Telefone VARCHAR2(15),
    Email VARCHAR2(100),
    CPF VARCHAR2(14) UNIQUE
);

CREATE TABLE Funcionario (
    Id_Funcionario NUMBER PRIMARY KEY,
    Nome_Completo VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    Salario NUMBER(10,2)
);

CREATE TABLE Produto (
    Cod_Produto NUMBER PRIMARY KEY,
    Nome_Produto VARCHAR2(100),
    Estoque NUMBER,
    Preco NUMBER(10,2)
);

CREATE TABLE Log_Auditoria (
    Id_Log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Acao VARCHAR2(255),
    Data_Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Dispositivo (
    Id_Dispositivo NUMBER PRIMARY KEY,
    Tipo VARCHAR2(50),
    Modelo VARCHAR2(50),
    Condicao VARCHAR2(100),
    Id_Cliente NUMBER,
    CONSTRAINT fk_disp_cli FOREIGN KEY (Id_Cliente) REFERENCES Cliente(Id_Cliente)
);

CREATE TABLE Chamado (
    Id_Chamado NUMBER PRIMARY KEY,
    Id_Cliente NUMBER,
    Id_Dispositivo NUMBER,
    Tipo_Servico VARCHAR2(20) CHECK (Tipo_Servico IN ('Venda', 'Conserto')),
    Descricao VARCHAR2(255),
    Data_Inicio DATE,
    Data_Termino DATE,
    Status VARCHAR2(20) CHECK (Status IN ('Não Iniciado', 'Iniciado', 'Terminado')),
    CONSTRAINT fk_cham_cli FOREIGN KEY (Id_Cliente) REFERENCES Cliente(Id_Cliente),
    CONSTRAINT fk_cham_disp FOREIGN KEY (Id_Dispositivo) REFERENCES Dispositivo(Id_Dispositivo)
);


CREATE TABLE Itens_Chamado (
    Id_Chamado NUMBER,
    Cod_Produto NUMBER,
    Qtde_Vendida NUMBER,
    Valor_Unitario NUMBER(10,2),
    PRIMARY KEY (Id_Chamado, Cod_Produto),
    CONSTRAINT fk_itens_cham FOREIGN KEY (Id_Chamado) REFERENCES Chamado(Id_Chamado),
    CONSTRAINT fk_itens_prod FOREIGN KEY (Cod_Produto) REFERENCES Produto(Cod_Produto)
);

CREATE TABLE Funcionario_Chamado (
    Id_Funcionario NUMBER,
    Id_Chamado NUMBER,
    PRIMARY KEY (Id_Funcionario, Id_Chamado),
    CONSTRAINT fk_fc_func FOREIGN KEY (Id_Funcionario) REFERENCES Funcionario(Id_Funcionario),
    CONSTRAINT fk_fc_cham FOREIGN KEY (Id_Chamado) REFERENCES Chamado(Id_Chamado)
);